export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'



export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'


export const OBTENER_PRODUCTOS_ELIMINAR = 'OBTENER_PRODUCTOS_ELIMINAR'
export const PRODUCTO_ELIMINAR_EXITOSO = 'PRODUCTO_ELIMINAR_EXITOSO'
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR'

export const OBTENER_PRODUCTOS_EDITAR = 'OBTENER_PRODUCTOS_EDITAR'
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO'
export const PRODUCTO_EDITAR_EXITOSO = 'PRODUCTO_EDITAR_EXITOSO'
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'